
services:
  db:
    image: postgres:15
    container_name: nuxt_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/devdb
      NODE_ENV: development
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev && npm run dev"

volumes:
  postgres_data:
